steps:
  - name: 'gcr.io/$PROJECT_ID/node-sbt'
    args:
      - 'yarn'
      - 'install'

  - name: 'gcr.io/$PROJECT_ID/node-sbt'
    args:
      - 'sbt'
      - 'clean'
      - 'fullOptJS'

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['stage']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cloudBuildSlackNotifications
      - --entry-point
      - entryPoint
      - --trigger-topic
      - cloud-builds
      - --runtime
      - nodejs10
      - --source
      - ./target/dist

timeout: 1200s # 20min
