name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'

    - name: Show env versions
      run: |
        node -v
        yarn -v
        java -version

    - name: Install sbt
      run: |
        echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt

    - name: Prepare for testing
      run: |
        yarn install

    - name: Run test
      run: |
        export SBT_OPTS="-Xms4G -Xmx4G -Xss6M -XX:ReservedCodeCacheSize=512M -XX:MaxMetaspaceSize=1024M"
        sbt clean lint test
