name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: olafurpg/setup-scala@v5
      with:
        java-version: 'zulu@1.11'

    - name: Show env versions
      run: |
        node -v
        yarn -v
        java -version

    - name: Prepare for testing
      run: |
        yarn install

    - name: Run test
      run: sbt clean lint test
